version: '3'

services:

  web:
    build:
      dockerfile: Dockerfile
      context: custom-fpm
    ports:
      - "80:80"
    volumes:
      - "./custom-fpm/nginx.conf:/etc/nginx/nginx.conf"
      - "./symfony_skeleton:/var/www:cached"
